name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Hatch
        run: python -m pip install --upgrade pip hatch
      - name: Create env
        run: hatch env create
      - name: Format check
        run: hatch run format --check
      - name: Lint
        run: hatch run lint
      - name: Markdown Format check
        run: hatch run mdfmt-check
      - name: Typecheck
        run: hatch run typecheck
      - name: Tests
        run: hatch run test
